### ISSUE TITLE
RFC: Remove the frontmatter description from blog posts

### ISSUE THREAD

**Issue by chrismwilliams** [chrismwilliams/astro-theme-cactus#100]
# Summary

Currently, the frontmatter description property is being used in 3 places.
1. The SEO meta description 
2. Displayed at the top of a single blog post, just below the title 
3. A summary when linking to a post

This change would be removing no.2.

# Proposal

It doesn't seem particularly helpful to include, what is essentially a meta description, within the body of a post. By removing it, it would allow users to add content in any order they wish, and to provide a description better fitting for SEO purposes.

# Request

Looking for feedback and thought's on this as it would/could effect how you write both the frontmatter and body of every post going forward. I'm also contemplating removing no.3, however, this would require pulling content from the start of the post's body, which may not be to everyone's liking.

**Comment by Giuliopime** [comment]
I do agree that the seo description being shown in a post page just below the title isn't ideal for me, I removed it in fact.

**Comment by kdmcguire** [comment]
> Same here, would be happy for that to be removed 👍
> 
> Edit: had second thoughts, see below

Have had a second thought: including it in the page is quite useful if you want to use it as the `p-summary` in the `h-entry` microformat.

E.g. https://kieran-mcguire.uk/posts/monday-ritual/

**Comment by chrismwilliams** [comment]
Thanks @Giuliopime @kdmcguire. This has now been removed in [v3.0](https://github.com/chrismwilliams/astro-theme-cactus/commit/60be86f2fea6d442c32bffcc6c9db96085c615de#diff-359c4eaa0bd37ec02ce799ef9afa137ce00e1296b549a3349832481361303977L85).

I fell on the notion of users have the option to add it in if required, rather than having to remove it and/or figuring out why it was appearing at the top of a post and having to hunt it down.

Thanks again for your help
