### ISSUE TITLE
Logo change

### ISSUE THREAD

**Issue by Thodoris1999** [chrismwilliams/astro-theme-cactus#134]
First of all thank you for the awesome template!

This may end up to be more of a general question, rather than an issue to this repository. Is there preferred way to change the logo on the website? I currently have a single svg image, but there are many different logo image placed around the project (afaik 512x512.png, 912x192.png, favicon.ico, icon.svg, apple-touch-icon.png and the one inline in Base.astro). It feels that this procedure can be automated so as a frontend development noob I was wondering if there are any automations or best practices when it comes to changing the logo.

**Comment by chrismwilliams** [comment]
Hi @Thodoris1999, yeah there are quite a few steps to get it how you want. Unfortunately, that's the nature of the web dev beast and accounting for the many use-cases that pop-up, there isn't always a one size fits all approach. There are a mass of opinions on sizes and formats but I quite like [this article](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs) which you may find helpful.

Personally, for icon/logo generation I usually reach for an application such as [Figma](https://www.figma.com) and a couple of popular plugins to generate it all for me once the svg has been created. 

Hope that helps.

**Comment by Thodoris1999** [comment]
Thank you for explaining! I wasn't really familiar with the space and just wanted to make sure
