### ISSUE TITLE
No image on Social Image post

### ISSUE THREAD

**Issue by EvgeniiaVak** [chrismwilliams/astro-theme-cactus#161]
Here is how the Example Social Image post looks like. Shouldn't there be an image?

<img width="1447" alt="Screenshot 2023-11-14 at 18 05 20" src="https://github.com/chrismwilliams/astro-theme-cactus/assets/27793901/ecdd2a6f-8392-4f7d-921a-bba7adee51fb">

**Comment by chrismwilliams** [comment]
Thanks for this @EvgeniiaVak. 
I've updated the title to clarify this post is meant to detail adding a custom open graph image.
