### ISSUE TITLE
how to change title from "Astro Cactus"?

### ISSUE THREAD

**Issue by Ziggomatic** [chrismwilliams/astro-theme-cactus#162]
sorry dumb question

**Comment by maathuran** [comment]
Hey @Ziggomatic,

You can change it https://github.com/chrismwilliams/astro-theme-cactus/blob/64ae486e7e63d74d3c5cdc5c8d0ccbc23aecc77d/src/components/layout/Header.astro#L67

**Comment by Ziggomatic** [comment]
thank you!
