### ISSUE TITLE
Feature Request: Netlify Image CDN using Astro Adapter

### ISSUE THREAD

**Issue by theapplegates** [chrismwilliams/astro-theme-cactus#185]
https://www.netlify.com/blog/astro-netlify-adapter/

Is this something that would be easy to implement?
I tried to do it but could not get it to work.
But for those who code it might be easy. Any thoughts?
Paul

**Comment by theapplegates** [comment]
Once I found the correct instructions it seems I was able to get it to work.
Seeing the images served by cloudfront.net shows it's working. So I'm closing the ticket.
Thanks
<img width="1158" alt="SeemsToWork" src="https://github.com/chrismwilliams/astro-theme-cactus/assets/27178137/50446ce0-f13f-4fb4-b153-25e2058635d4">

Paul

**Comment by chrismwilliams** [comment]
Hi @theapplegates,

It's not something I've tried, however, reading the [release notes](https://www.netlify.com/blog/astro-netlify-adapter/) and the [adaptor docs](https://docs.astro.build/en/guides/integrations-guide/netlify/#netlify-image-cdn-support) it should work without any additional input/code other than adding the adaptor itself. But yes, looking at your network requests the two non-cache images are coming from a cdn so it looks like you're sorted.
