### ISSUE TITLE
No Issue just a thought

### ISSUE THREAD

**Issue by theapplegates** [chrismwilliams/astro-theme-cactus#2]
Loving your Astro theme. Have you considered sending it to some sites such as https://jamstackthemes.dev, you would be the first Astro theme there, or even better submitting it to https://astro.build/themes/ ?

I understand you might not have time to maintain Cactus full time, but I love the site and feel others will too.
Anyway thanks for the hard work, looking forward to whatever you add to the theme.
Sorry for posting this as an issue, but I could not find your contact info.
Paul

**Comment by chrismwilliams** [comment]
Hi Paul. Thanks so much for the message, I really appreciate you taking the time to say that, and glad you like the theme. Tbh I created Cactus as a means to learn about Astro and island architecture, which I hadn't heard about until very recently, with a view to using it more for other projects as they (Astro) move to 1.0.

In terms of promoting it, the only thing I thought of doing was dropping it into their discord so thank you for the suggestions. There are a few current issues that need fixing and I intend to add a few things, time permitting, soon. I do though want to keep up with breaking changes as the team add more features as I really like what they're doing.
Thanks again
Chris

**Comment by theapplegates** [comment]
You're welcome. I understand, I did forget about their discord. They helped me when I posted a question. I'm not a developer but I can Google and view source code.
