### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by theapplegates** [chrismwilliams/astro-theme-cactus#22]
How do you change the font? I have tried examples from https://tailwindcss.com/docs/font-family, but nothing seems to work. I made sure the pages were not in the browser's cache. There has to be something I am missing.
Thanks
Paul

**Comment by chrismwilliams** [comment]
Hey Paul, yep that should be mentioned in the README, so thanks for that. I've just pushed an update, 989d71b, to show where the font stack is set and how to change it. Let me know if you have any trouble or see anything that needs changing. I'll keep this open in the meantime for you.

Thanks again
Chris

**Comment by theapplegates** [comment]
It worked great. Thanks for the help.

**Comment by chrismwilliams** [comment]
Hey @logicman, the styles for posts are set via the [@tailwindcss/typography](https://tailwindcss.com/docs/typography-plugin) plugin. Unfortunately, the plugin doesn't follow the base size which means you'll also need to add the size via the `prose` variant.

[Here](https://tailwindcss.com/docs/typography-plugin#applying-a-type-scale) you can see how to change the body font size, which you can add to [this line](https://github.com/chrismwilliams/astro-theme-cactus/blob/b9249c2055ebbe040ac557d82744f63d1ffb120a/src/layouts/BlogPost.astro#L30) in the code.

Hope that helps.
