### ISSUE TITLE
Issue while building...

### ISSUE THREAD

**Issue by logicman** [chrismwilliams/astro-theme-cactus#223]
Nice work on the theme. However, when I run 'yarn run build", I get the following errors....

src/layouts/Base.astro:7:22 - error ts(2307): Cannot find module '@/components/SkipLink' or its corresponding type declarations.

7 import SkipLink from "@/components/SkipLink";
                       ~~~~~~~~~~~~~~~~~~~~~~~
src/layouts/Base.astro:6:20 - error ts(2307): Cannot find module '@/components/layout/Footer' or its corresponding type declarations.

6 import Footer from "@/components/layout/Footer";
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/layouts/Base.astro:5:20 - error ts(2307): Cannot find module '@/components/layout/Header' or its corresponding type declarations.

5 import Header from "@/components/layout/Header";
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
....

**Comment by logicman** [comment]
Thanks. I have used your template with this command:
npm create astro@latest -- --template chrismwilliams/astro-theme-cactus

How do I update it with the changes you have made? Sorry, newbie question.

**Comment by chrismwilliams** [comment]
No worries, it's a common question and unfortunately there is no 'right' way, as explained [here](https://github.com/chrismwilliams/astro-theme-cactus/issues/43#issuecomment-1412306012). 

For me personally, I run a heavily modified version of this template, have two separate git remotes and pull in the changes when necessary. Whichever method you take, though, be prepared for some merge conflicts which are inevitable as these things are personalised.

Hope that helps.
