### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by logicman** [chrismwilliams/astro-theme-cactus#226]
The latest version breaks the dark mode toggle button on the top right. 

npm create astro@latest -- --template chrismwilliams/astro-theme-cactus

**Comment by chrismwilliams** [comment]
Hey @logicman, unfortunately astro@4.2.5 and later have an issue which can only be seen in dev mode, which is affecting this themes' dark mode logic. Downgrading to v4.2.4 is the best solution for now.

**Comment by logicman** [comment]
Excellent that worked! Hope the issue can be fixed for the latest version in the near future. Thanks in advance.
