### ISSUE TITLE
table don't works

### ISSUE THREAD

**Issue by X7md** [chrismwilliams/astro-theme-cactus#24]
I was working to make [RTL] version of this theme

https://github.com/X7md/astro-theme-cactus-rtl

 but I notice issue...

![image](https://user-images.githubusercontent.com/54203033/191367453-a691291f-5f34-4707-8a85-5906dd6f21bc.png)

and as temporary workaround I use this:

``sh
npm i remark-gfm
``

```js
//astro.config.ts
import remarkGfm from "remark-gfm"
integrations: [
		mdx({
			// add this
			remarkPlugins:[[remarkGfm, {}]]
		}),
		tailwind({
			config: { applyBaseStyles: false },
		}),
		image(),
		sitemap(),
	],
```

**Comment by chrismwilliams** [comment]
Hi @X7md, sorry I've only just seen this. I'll have to take a closer look at this, time permitting over the next week, as I'm not sure if its Astro or the mdx integration, as [@astrojs/mdx v0.11.1](https://github.com/withastro/astro/blob/main/packages/integrations/mdx/CHANGELOG.md#0111) adds GFM by default so you shouldn't require a remark plugin.

I'll let you know if I find anything

**Comment by chrismwilliams** [comment]
Closing due to being an upstream issue
