### ISSUE TITLE
Console Warning: astro:content...

### ISSUE THREAD

**Issue by ColeTownsend** [chrismwilliams/astro-theme-cactus#243]
`astro:content is only supported running server-side. Using it in the browser will lead to bloated bundles and slow down page load. In the future it will not be supported.`

After a bunch of deugging, this is caused by the barrel import file in `@/utils` in the `ThemeProvider` and `ThemeToggle`

Happy to open a PR but does require shifting around quite a bit so wanted to open this issue first. Thanks for making this theme!

**Comment by chrismwilliams** [comment]
Thanks @ColeTownsend and thanks for the helpful info. This should now be fixed in #244 but let me know if otherwise.
