### ISSUE TITLE
Hide Posts from view

### ISSUE THREAD

**Issue by etsde** [chrismwilliams/astro-theme-cactus#245]
It would be great if it'd be possible to set a parameter to hide posts from the public list but also is not a draft: so to say a hidden post; only accessible via a direct link.

**Comment by chrismwilliams** [comment]
Hey @etsde thanks for the suggestion. There are quite a few different solutions one could do to implement this which probably means that its not something I'm looking to add to the theme atm.

Off the top of my head you'd need to decide if said posts have/are:
- omitted from web crawlers (robots.txt)
- removed from the sitemap
- removed from the rss feed
- an og:image
- tags that aren't included elsewhere

There's probably more I'm forgetting but yeah, it would require a similar boolean flag as the draft feature does.
