### ISSUE TITLE
How does one create an account at webmention.io?

### ISSUE THREAD

**Issue by NickHodges** [chrismwilliams/astro-theme-cactus#249]
Thanks for a great site template.  Loving it.

However, this post:  https://astro-cactus.chriswilliams.dev/posts/webmentions/

says:

2. Create an account @ [Webmention.io](https://webmention.io/).

And I go there, and there is no way to create an account. 

Can you maybe clarify that?  I can't seem to get webmentions running at all.

**Comment by chrismwilliams** [comment]
Thank @NickHodges. 

I've just  pushed a change, #250,  that _should_ clarify it a bit better if you re-visit the webmention post again. Essentially, the post is split into two sections, a [TLDR](https://astro-cactus.chriswilliams.dev/posts/webmentions/#tldr), and a longer [detailed version](https://astro-cactus.chriswilliams.dev/posts/webmentions/#sign-up-to-webmentionio). 

If you've done [part 1](https://astro-cactus.chriswilliams.dev/posts/webmentions/#add-links-to-your-profiles), you just need to enter your websites' url into [webmention.io](https://webmention.io/), where it says "Web Sign-In" to continue.

Let me know if the update helps, or requires any changes, but hopefully you're able to get it sorted.

**Comment by NickHodges** [comment]
Great!  Thanks!   And thanks for a great Astro template. I'm using it here:  https://nickhodges.com
