### ISSUE TITLE
Formatting Post Preview Descriptions

### ISSUE THREAD

**Issue by nhtsai** [chrismwilliams/astro-theme-cactus#257]
I was looking to add the description to the post previews, so I added `withDesc` to /posts. However, the descriptions appear on the right side of the post titles (see image below). 

Is there any way to move the descriptions to underneath the titles? Thanks!

![postpreview](https://github.com/chrismwilliams/astro-theme-cactus/assets/22184131/848c7584-69c8-4292-b61c-3e4f20d81e92)

**Comment by chrismwilliams** [comment]
Hey @nhtsai I've just updated the theme in #258, it's a small change to [this line](https://github.com/chrismwilliams/astro-theme-cactus/blob/1a3ff802238fa501bfd8f90ebac70e7dd710c2b4/src/pages/posts/%5B...page%5D.astro#L59), so hopefully that fixes your issues
