### ISSUE TITLE
Favicon and icon problems

### ISSUE THREAD

**Issue by fccapria** [chrismwilliams/astro-theme-cactus#26]
Hi, today I tried to create a site with this theme but I have some problems with the favicon and the icon on the header.
If I replace the favicon and the icons it will be always rendered with the "stock" image.

Where am I doing wrong?

**Comment by chrismwilliams** [comment]
Hi @fccapria. For the favicon, it does sound like it's being cached by the browser and needs a full refresh? I can't think of anything else, as the only references to it are in [src/components/BaseHead.astro](https://github.com/chrismwilliams/astro-theme-cactus/blob/e06c77f92a16540f8a744eb48caaafa6535d63b7/src/components/BaseHead.astro#L29), and if you've changed both then it should have changed.

The icon in the header though is an inline svg, which will change if you add your own to [src/components/Header.astro](https://github.com/chrismwilliams/astro-theme-cactus/blob/e06c77f92a16540f8a744eb48caaafa6535d63b7/src/components/Header.astro#L31).

Unfortunately I can't be much more helpful than that unless I can see your code/example. Hope that helps and feel free to keep this open until you get it fixed.

**Comment by fccapria** [comment]
Thanks for the reply! I'll try tomorrow and I'll let you know!

**Comment by fccapria** [comment]
Thanks a lot, I solved it! It was as you said!
Going to try the page in incognito mode, the favicon is the new one.
I don't know why deleting the cookies doesn't fix it, but the important thing is that there is indeed the new favicon.
Even for the image in the header I solved!
Thank you very much!
