### ISSUE TITLE
How to use two different posts?

### ISSUE THREAD

**Issue by Hankyu-Kim** [chrismwilliams/astro-theme-cactus#264]
Hello, thank you for the great theme.

By the way, I tried to organize my posts into two different menus. I attempted to use tags to display only posts related to a 'specific theme,' but things got complicated with files like [...page].astro, [slug].astro, and post.ts.

I also tried duplicating these files and changing CollectionEntry<"post"> to CollectionEntry<"something else">, but that didn’t work either.

Do you have any good references or can you explain how to create an additional post type to differentiate them?

**Comment by Hankyu-Kim** [comment]
Thank you, the way refactoring references of CollectionEntry<"post"> to CollectionEntry<"post" | "something else"> where their schemas overlap for re-use helped me.

**Comment by Hankyu-Kim** [comment]
Reference : 
here is my repo : https://github.com/Hankyu-Kim/hankyukim.com
and here is my website : https://hankyukim.com/

the main page posts should be CollectionEntry<"review">
and Network menu posts should be CollectionEntry<"post">

**Comment by chrismwilliams** [comment]
You're probably going to have to create a union return type and query both "post" and "something else" if you want to reuse functions. 

Just a quick note though, if your "reviews" are the "something else", they haven't been added to [Astro's content collection](https://docs.astro.build/en/guides/content-collections/#defining-collections) with your current config, and will error out. As they mention, the 'key should match your collection directory name'
