### ISSUE TITLE
Dependency install issues on new project

### ISSUE THREAD

**Issue by BrodyJackson** [chrismwilliams/astro-theme-cactus#286]
Hi there!

Apologies if this is related to my environment but I believe it is coming from somewhere within the project dependencies. I'm currently trying to get the template up and running but an _npm install_ on a newly cloned project results in dependency resolution errors. I've attached a screenshot below. Let me know if I can help in any way! 

![image](https://github.com/user-attachments/assets/299d41e8-dd53-4570-9bc6-3cbed638e645)

**Comment by chrismwilliams** [comment]
Hi @BrodyJackson,

Hopefully this should now be sorted (if you haven't found a fix already) with #290. I was hoping that all the eslint plugins the theme uses would be v9 compatable now, but I've decided to move over to biome instead of waiting.

**Comment by BrodyJackson** [comment]
Hey @chrismwilliams , 

Just pulled things down a looked again and it's definitely fixed. Thanks so much for the quick fix on that! Love the project. All the best!
