### ISSUE TITLE
Hamburger menu not working on post page

### ISSUE THREAD

**Issue by theapplegates** [chrismwilliams/astro-theme-cactus#3]
The hamburger menu is not working on the blog post page. You can click it but nothing happens. When viewed using developer tools nothing is showing at all. No error, no network request, nothing.

Also Writings -> Blog, in the footer was not changed when all Writings were all changed to Blog. Just that one was missed.

**Comment by theapplegates** [comment]
You're welcome. It's a weird one, hopefully they can help. Take your time. I think I'm your only active user 😂

**Comment by theapplegates** [comment]
It says I "commented and opened". I hope that does not mean re-opened. If you closed it you can re-open it. I will close it now. Hopefully I'm doing this right.

**Comment by sononicola** [comment]
Hello
Is it still buggy right? 
this is from your demo app: menu isn't working
![immagine](https://user-images.githubusercontent.com/46779155/187855776-9abf5393-3276-493b-a921-db767d073675.png)

**Comment by chrismwilliams** [comment]
Hi @sononicola yeah that is weird, testing it in dev it seems to works fine but upon building it doesn't, and it's only on blog pages.
I've just updated astro in e06c77f and it seems to work as it should so hopefully it wont reappear, and it's sorted your end.
Thanks again

**Comment by sononicola** [comment]
I can confirm that with these new dependencies now it works!

One side thing: how do you produce the `pnpm-lock.yaml` file?
I had some trouble deploying it in Netlify (I was using the old version, and manually updated only the `package.json`). Ifinally solved by brutally copy pasting the whole file from your repo 😂

**Comment by chrismwilliams** [comment]
Okay cool thanks for letting me know!

Oh yeah that sounds a pain! I just use pnpm with [pnpm i](https://pnpm.io/cli/install) to install dependancies, which creates the `pnpm.lock.yaml` file. Can't say I've had a problem with netlify using pnpm though, apart from workspaces, but that doesn't apply here. 

I hope it fixes itself soon 👍
