### ISSUE TITLE
Generate robots.txt from config

### ISSUE THREAD

**Issue by acherunilam** [chrismwilliams/astro-theme-cactus#31]
Instead of hardcoding [robots.txt](https://github.com/chrismwilliams/astro-theme-cactus/blob/main/public/robots.txt), can we use the [astro-robots-txt](https://github.com/alextim/astro-lib/tree/main/packages/astro-robots-txt) integration to generate it from config? It'll be less error-prone if you want to customize it.

I'm happy to submit a PR if this is something you'd like.

**Comment by chrismwilliams** [comment]
@acherunilam thank you for this. ATM I'm thinking of waiting this one out and perhaps hoping for a 1st party integration. You are right in that I'm relying on people reading the docs to change the site url so I may circle round and add it in the future.

I'll keep this open for a bit and take a look at a few other astro templates to get a view of the community/landscape and see where people are at.

Thanks again for the suggestion
