### ISSUE TITLE
Keyboard elements do not show up in dark mode

### ISSUE THREAD

**Issue by FelixNgFender** [chrismwilliams/astro-theme-cactus#316]
I'm just a casual user of the template and not familiar with the codebase, but I'd be willing to help if someone could point out where I should look to fix this. Thank you!

![image](https://github.com/user-attachments/assets/944329aa-841b-4703-aaa3-4a393b111645)

![image](https://github.com/user-attachments/assets/b0cbd208-c811-43a9-80ca-70db05dc3cd2)

**Comment by chrismwilliams** [comment]
Hey @FelixNgFender, I'm not sure where the above is coming from, but I'm guessing this is markdown? 
If it is, it looks like [typography](https://github.com/tailwindlabs/tailwindcss-typography) isn't picking it up / being overruled. I will need a bit more code or link to help further

**Comment by FelixNgFender** [comment]
```md
| Action                | Shortcut                                   |
| --------------------- | ------------------------------------------ |
| Vertical split        | <kbd>Alt+Shift++</kbd>                     |
| Horizontal split      | <kbd>Alt+Shift+-</kbd>                     |
| Auto split            | <kbd>Alt+Shift+d</kbd>                     |
| Switch between splits | <kbd>Alt</kbd> + arrow keys                |
| Resizing a split      | <kbd>Alt+Shift</kbd> + arrow keys          |
| Close a split         | <kbd>Ctrl+Shift+W</kbd>                    |
| Maximize a pane       | <kbd>Ctrl+Shift+P</kbd> + Toggle pane zoom |
```

Here's the markdown for that.
