### ISSUE TITLE
Generate RSS feed

### ISSUE THREAD

**Issue by acherunilam** [chrismwilliams/astro-theme-cactus#32]
Can we add support for RSS feeds using the [@astrojs/rss](https://docs.astro.build/en/guides/rss/) integration?

I'm happy to submit a PR if this is something you'd like.

**Comment by chrismwilliams** [comment]
Hey @acherunilam thanks for the suggestion. I've made a quick pass at the integration. Feel free to add anything to #33, and I'll get it merged.

Thanks again

**Comment by chrismwilliams** [comment]
Done via #33. Thanks again @acherunilam
