### ISSUE TITLE
analytic

### ISSUE THREAD

**Issue by thuanowa** [chrismwilliams/astro-theme-cactus#35]
https://astro.build/integrations/analytics/

**Comment by chrismwilliams** [comment]
Hi @thuanowa.

Not quite sure if you want me to add an analytic integration to the template, or you require some help. 

If it's the latter, #36 which I'll merge soon should hopefully help you. If it's the former, as explained in #36, I can't commit to a single solution as use cases are so different, and so hopefully the README should help people choose what suits best.

Hope that make sense, and let me know if you require more

**Comment by thuanowa** [comment]
close #36
