### ISSUE TITLE
Tag problems

### ISSUE THREAD

**Issue by Hasenpfote** [chrismwilliams/astro-theme-cactus#40]
Hi!
I have been using it via "Use this template" since the weekend.
So I think it is v1.5.2.

### condition

When upper-case letters are mixed in tags of front-matter.  

### cause

I believe the problem lies in the string comparison.  

The part that unifies duplicate tags into lowercase.  
https://github.com/chrismwilliams/astro-theme-cactus/blob/58caa51c6a20ab9f73178ebe9c9266c99c5cbef1/src/utils/post.ts#L12

The part that compares with the front-matter tags.  
https://github.com/chrismwilliams/astro-theme-cactus/blob/58caa51c6a20ab9f73178ebe9c9266c99c5cbef1/src/pages/tags/%5Btag%5D/%5B...page%5D.astro#L16

### condition

When upper-case letters are mixed in tags of front-matter.

### cause

The URL points to a page in uppercase, but the actual page is in lowercase.  

The part that generates tags.  
https://github.com/chrismwilliams/astro-theme-cactus/blob/58caa51c6a20ab9f73178ebe9c9266c99c5cbef1/src/utils/post.ts#L23

The part that uses them.  
https://github.com/chrismwilliams/astro-theme-cactus/blob/58caa51c6a20ab9f73178ebe9c9266c99c5cbef1/src/pages/tags/index.astro#L23

Thank you.

**Comment by chrismwilliams** [comment]
Hi @Hasenpfote great catch and thank you for making it so clear.

I've pushed a fix #41, let me know if you get chance to try it and will get it merged if it fixes your issues.

**Comment by Hasenpfote** [comment]
Hi @chrismwilliams.
This PR worked perfectly as expected for me.
Thanks for the quick response!
