### ISSUE TITLE
Question: where are the icons from?

### ISSUE THREAD

**Issue by gotofritz** [chrismwilliams/astro-theme-cactus#49]
Hi, thanks for the great theme. I wanted to change some of the icons - for example I don't use twitter but mastodon - and wanted to find icons in the same style. Where are they from?

**Comment by chrismwilliams** [comment]
Hi @gotofritz and thanks. Yeah thank you for reminding me I should add a code comment as well, I got them from [tabler icons](https://tablericons.com/) but it doesn't look to have a mastodon icon, nor my other go-to [iconoir](https://iconoir.com/) unfortunately

**Comment by gotofritz** [comment]
Oh shame - still, it has LinkedIn and a few others, so it's not so bad. Thanks!
