### ISSUE TITLE
Visual hierarchy in post header

### ISSUE THREAD

**Issue by Elwafi-Elmehdi** [chrismwilliams/astro-theme-cactus#50]
![Screenshot_20230221_120943_com.brave.browser.jpg](https://user-images.githubusercontent.com/77673506/220329633-05807b6f-2832-4845-90ef-9c3fcd2f6c09.jpg)

**Comment by Elwafi-Elmehdi** [comment]
Hey, @chrismwilliams

I hope you are doing fine, thank you for submitting that PR in my project I really appreciate it.

A small problem can be fixed by adding a margin to the post's header, to let the user differentiate between the post header and post metadata. You can see what I mean in the image below

**Comment by chrismwilliams** [comment]
Hey @Elwafi-Elmehdi, np, yeah it does look a bit cramped. Check out #56 and let me know what you think
