### ISSUE TITLE
auto hide "table of contents" when didn't have heading

### ISSUE THREAD

**Issue by thuanowa** [chrismwilliams/astro-theme-cactus#51]
![image](https://user-images.githubusercontent.com/40050527/220403731-abe689c5-cf1f-4a42-b581-d49aa5d2b6a0.png)

**Comment by thuanowa** [comment]
demo post don't have heading: https://thuanowa.com/posts/omg-oh-my-girl-2022/

**Comment by chrismwilliams** [comment]
Hey @thuanowa thank you for find this. I've included this in [v2.1.0](https://github.com/chrismwilliams/astro-theme-cactus/releases/tag/v2.1.0) which stop this from happening. Let me know and we'll get this closed, thanks again
