### ISSUE TITLE
"Table of contents" styling different heading

### ISSUE THREAD

**Issue by thuanowa** [chrismwilliams/astro-theme-cactus#52]
![image](https://user-images.githubusercontent.com/40050527/220404597-964ce811-3741-4213-a433-07349d71a784.png)

Ideas:
```bash
[TOC]
# heading 1
....## heading 2
........### heading 3
```

**Comment by chrismwilliams** [comment]
Hi @thuanowa thanks for highlighting this. I've add a hierarchy for different headings which you can checkout in [v2.1.0](https://github.com/chrismwilliams/astro-theme-cactus/releases/tag/v2.1.0). Let me know what u think and we'll get this closed, thanks again
