### ISSUE TITLE
CSS Grid for blog posts: main column expands if content is too wide

### ISSUE THREAD

**Issue by gotofritz** [chrismwilliams/astro-theme-cactus#53]
If some of the content in the main content column of a blog post is too wide, the main area (the `<article>`) expands and squashes the content navigation (the `<aside>`). That's because it is define as a grid with `3fr 1fr`, which gets treated as `minmax(auto,  3fr) 1fr`. That should be changed to `minmax(0,  3fr) 1fr`. There are two ways i know of doing that with Tailwind, either `grid-cols-[minmax(0,3fr)_1fr]` or changing it to a 4 cols layout. I will submit a PR with the latter approach

**Comment by chrismwilliams** [comment]
Hi @gotofritz thank you for this. We may need to adjust this slightly to deal with #51 however, which isn't something I'd thought about tbh. 

Just thinking out loud, one way could be to optionally render the entire `<aside>` depending on the `headings` length, and in turn change `col-span-3` to `col-span-4` for `<article>` in its absence, perhaps with astro's `class:list` directive.

Let me know what you think as I'm sure there's a better/clearer way, but I do think it's best for the `<article>` to take up the entire width in the situation when the `<aside>` isn't required/rendered.

**Comment by chrismwilliams** [comment]
As an alternative to the above, just add `col-span-1` to the `<aside>`, and allow the `<article>` to grow the remainder without the set `col-span-3/4`.
