### ISSUE TITLE
RSS Link

### ISSUE THREAD

**Issue by vegetablesB** [chrismwilliams/astro-theme-cactus#58]
Hi, I just tried the RSS. The link seems to be not functioning properly. 

Upon investigating the issue, I discovered that the current RSS link is: **example.com/hello-world**
However, it appears that the correct link should be: **example.com/posts/hello-world**

the code `link: post.slug,` should the code looks something like this ```link: `/posts/${post.slug}/`,``` ? in [rss.xml.ts](https://github.com/chrismwilliams/astro-theme-cactus/blob/main/src/pages/rss.xml.ts)

**Comment by chrismwilliams** [comment]
Hi @vegetablesB, thanks for picking this up and your help, hopefully it should be fixed now
