### ISSUE TITLE
Hot reloading is not working

### ISSUE THREAD

**Issue by eRaMvn** [chrismwilliams/astro-theme-cactus#61]
Thanks for sharing the template but when I tried to use it, I could not get hot reloading to work. I am not sure if this is related to this issue https://github.com/withastro/astro/issues/4419

**Comment by eRaMvn** [comment]
nvm, I think this is the issue related to WSL2. When I switched to Mac, it worked without issues

**Comment by chrismwilliams** [comment]
Hi @eRaMvn no worries, and thanks for the update
