### ISSUE TITLE
Layout issue with scroll bar.

### ISSUE THREAD

**Issue by randomn4m3** [chrismwilliams/astro-theme-cactus#64]
There is a layout issue. Pages with a scroll bar don't have the same width as pages without a scroll bar.
As an example you check: [without scroll bar](https://astro-theme-cactus.netlify.app/posts/missing-content/) and [with scroll bar](https://astro-theme-cactus.netlify.app/posts/markdown-elements/).
I solved this issue by adding `overflow-y-scroll` in the body.

**Comment by Pratik280** [comment]
Hello @chrismwilliams I would like to kindly request for this issue to be assigned to me. Would it be possible for you, as the project maintainer, to make this assignment ? Thank you!

**Comment by randomn4m3** [comment]
Just open the two links in provided in two tabs on your laptop and switch from one the other. You will notice that the body is not in the same position.
I tried with Chrome and Firefox on Windows and with Safari, Chrome, and Firefox on macOS.

**Comment by chrismwilliams** [comment]
So I have looked at both and the only difference I can see (in px) is the `<article>`'s width, but that's because one blog has an aside (table of contents), and the other doesn't.

If that's what you mean then I'm unsure how `overflow-y-scroll` is going to make a difference in width.

**Comment by randomn4m3** [comment]
I see the HTML content in the first link as 15px bigger than the second link because the second is scrollable. So the body is in a different position.

**Comment by chrismwilliams** [comment]
Weird, as they're the same for me at every breakpoint regardless of device/browser. Could you provide a screenshot of the differences as I can't repro
