### ISSUE TITLE
Tiny white/black bar at the very top

### ISSUE THREAD

**Issue by bernwo** [chrismwilliams/astro-theme-cactus#65]
When in light (dark) mode, there is a thin black (white) bar at the very top when fully scrolled up the page. 

It is visible in both desktop and mobile version of the site.

**Comment by bernwo** [comment]
This can be fixed by changing the following codeblock in `global.css`:
```css
html {
    @apply h-full scroll-smooth border-t-2 border-textColor;
}
```
to:
```css
html {
    @apply h-full scroll-smooth border-t-0 border-textColor;
}
```

**Comment by chrismwilliams** [comment]
Hey @bernwo, yeah the bar is intentional/stylistic choice. 

If you would like to remove it, just delete the variants `border-t-2 border-textColor` above, hope that helps
