### ISSUE TITLE
SSL Error for og_image (and maybe something else?)

### ISSUE THREAD

**Issue by BeTmAsTeR** [chrismwilliams/astro-theme-cactus#68]
I wanted to try the Satori integration for creating open graph png images, i created a post in various social network with a link to the demo site but i got no og image.

This is the demo page i used https://astro-theme-cactus.netlify.app/posts/markdown-elements/

I watched the source for the og link and found the correct tag with the image 
`<meta property="og:image" content="https://www.astro-theme-cactus.netlify.app/og-image/markdown-elements.png">`

I opened the linked image
https://www.astro-theme-cactus.netlify.app/og-image/markdown-elements.png
and got an SSL error

error from firefox: SSL_ERROR_BAD_CERT_DOMAIN
error from chrome: NET::ERR_CERT_COMMON_NAME_INVALID

I think there is a misconfig in the demo site or in the theme itself

**Comment by chrismwilliams** [comment]
Hi @BeTmAsTeR thanks for opening this and letting me know.

I'm not redirecting subdomains to the apex and for some reason included the www in the site property. 

Anyway it should be fixed as of #69. Thanks again for your help
