### ISSUE TITLE
Mixed content error logs in console

### ISSUE THREAD

**Issue by pappasdev** [chrismwilliams/astro-theme-cactus#71]
For each of my posts, I am getting the following error in console.

`Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.`

I made sure the astro.config.ts file reflects my website thusly with https. Using example.com as a placeholder:
```js
export default defineConfig({
	site: "https://example.com/",
//...more code...
```
What else am I missing? This is the only area I recall specifying my domain. Or is it something else entirely? 

I also notice that the icon that switches the theme does not function on a post page either. May be in relation to this error?

None of these issues reflect at all during dev mode.

**Comment by chrismwilliams** [comment]
Hi @selfdivision. The only other place where the domain is required is the `robots.txt` file found [here](https://github.com/chrismwilliams/astro-theme-cactus/blob/0201b8a80f9e19795de1ccc6c455deb043eed90c/public/robots.txt#L4), however, I don't think that would cause this.

I can't see any issue currently with the demo site and the majority of resources are linked to the public folder, apart from images. I'd perhaps look at all the resources being requested on your site, via the network tab, and go from there, it may have something to do with your host/cdn

**Comment by selfdivision** [comment]
Ok, I'll wipe and reinstall and test the site live first. If there's no errors, I messed up somewhere along the way. If there are errors on a clean install, then it's probably something to do with my host. Thanks for reaching out.

**Comment by selfdivision** [comment]
I dug a little deeper with a fresh install, and it looks like cloudflare is not liking how the post urls are generated? I should say this only happens for each blog post link shown on the website. While the URL is https:// when hovered over with the mouse, the console log errors show the following on the /posts/ page for each post link:

'Blocked loading mixed active content “http://example.com/posts/post/”'

As you can see, it returns http://. I have not had this issue with my own astro theme, so it may be somewhere in the cactus theme code that generates the post urls? It seems it's a theme incompatibility with cloudflare as my domain host due to findings in network:

```
Status 301 Moved Permanently
location | http://example.com/posts/post/
report-to | {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/...the rest of the url...
}
server | cloudflare
```

**Comment by chrismwilliams** [comment]
It does seem like there is a compatibility issue with cloudflare. So the theme does build to cloudflare as well as netlify, [via pages](https://astro-theme-cactus.pages.dev/), and I can see the issue with the theme toggle on blog pages.

For some reason (and I can only see it currently on cloudflare) astro inlines the js for the toggle on none blog pages, which currently works, but for blog pages links to a .js file which doesn't exist, usually something like `hoisted.{some-hash}.js`. I can see from the built files on cloudflare that the `hoisted.{hash}.js` exists but with a different hash to the one linked, hence it breaking.

It's different on netlify however, where it just links to the hashed file, no inline, and is the same for every page. 

With that said, I don't think it's a theme issue, and is more an astro one and it's compatibility with cloudflare. I also can't see see the url issue you've mentioned on the pages demo? The theme does use @astrojs/prefetch for links, I wonder if it is again an astro/cloudflare compatibility issue, as the theme's url's aren't anything special, but when hovering links the prefetch plugin should pre-load assets in the background.

**Comment by chrismwilliams** [comment]
Quick update: I've just found out that Cloudflare have released a beta version of it's new [build tool](https://blog.cloudflare.com/moderizing-cloudflare-pages-builds-toolbox/) which you can [specify in a project's settings](https://developers.cloudflare.com/pages/platform/language-support-and-tools/).

I've just enabled it, as well as updating the build command to `pnpm build`, and it seems to have fixed the above issues. [Link to project](https://astro-theme-cactus.pages.dev/posts/markdown-elements/). Let me know how you get on but hopefully this fixes it.

**Comment by selfdivision** [comment]
Thanks for the update, but I only use cloudflare as domain hosting, so the issue still persists on my end.

**Comment by chrismwilliams** [comment]
Ah okay. Going by how the cloudflare build had similar issues, this is likely to be a node environment issue. As soon as I updated cloudflare to v2 (node ver: 18.16.0), the hoisting issue went away. 

Debugging issues between local and remote can be a bit of a pain, but I would start on the host side and go through the build logs. Sorry I can't be any more helpful than that
