### ISSUE TITLE
Merged declaration "post" cannot include a default export declaration 

### ISSUE THREAD

**Issue by kirso** [chrismwilliams/astro-theme-cactus#79]
The error happens in [posts].astro

```js
const { post } = Astro.props;
const { Content } = await post.render();
```
![image](https://github.com/chrismwilliams/astro-theme-cactus/assets/2138870/64c54221-252a-4291-b737-5581792a28b1)

**Comment by chrismwilliams** [comment]
Thanks for the report, this should be fixed by #80
