### ISSUE TITLE
Deploying error

### ISSUE THREAD

**Issue by fabriziodevincenzi** [chrismwilliams/astro-theme-cactus#87]
v2.5.1 conflicts with github distribution? when i create the deploy.yml file the action fails

Thank you

<img width="1767" alt="Screenshot 2023-07-08 alle 10 44 56" src="https://github.com/chrismwilliams/astro-theme-cactus/assets/102367490/95ccb1bd-2f32-43fa-9402-e151da62ff2e">

**Comment by chrismwilliams** [comment]
It's using an older version of node & pnpm, see [here](https://github.com/orgs/pnpm/discussions/6633#discussioncomment-6252187). Hope that helps
